Pretty Big - Displacements Now Have Lightmaps
lewa-j/Unity-Source-Tools pull request #45
Opened 2020-11-15 08:39 UTC by Fronkln

Ported over from Source to Unity, tested and confirmed. Biggest contribution yet!
![image](https://user-images.githubusercontent.com/17107072/99180425-46d54a80-2737-11eb-89a6-316d16dbd4c0.png)

2020-11-15 08:51 UTC, Fronkln commented
There seems to be a super rare interesting bug with this. Some of the displacements are placed with wrong offset

![image](https://user-images.githubusercontent.com/17107072/99180633-ddeed200-2738-11eb-8130-d14813fa45c3.png)

2020-11-15 10:07 UTC, Fronkln commented
The UV's might need to be flipped by 90 degrees for displacements

2020-11-15 11:28 UTC, lewa-j commented
Already solved this thing in a different project. Look here for reference https://github.com/lewa-j/vbsp-gles/blob/master/src/bsp_loader.cpp#L1014

2020-11-15 12:26 UTC, Fronkln commented
Alright, i'll take a look

2020-11-15 14:53 UTC, Fronkln commented
I believe its easier and better to just rewrite displacement code accordingly to the bsp loader you linked, i'll follow this up with another pull request if i manage to get it working

2020-11-15 20:53 UTC, Fronkln commented
Managed to fix it commit tomorrow

2020-11-16 07:53 UTC, Fronkln commented
![image](https://user-images.githubusercontent.com/17107072/99225924-e9560200-27f9-11eb-9a79-43912ea8e703.png)

2020-11-16 14:46 UTC, lewa-j requested changes

2020-11-16 14:46 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +               			mr.lightmapIndex = curLightmap;
Here

2020-11-16 14:46 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +                        int lightmapH = curFace.LightmapTextureSizeInLuxels[1] + 1;
here

2020-11-16 14:46 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +                        {
this entire block is a mess

2020-11-16 14:46 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +              		       (origLMUV[1] - origLMUV[0]) * invHeight,
here

2020-11-16 14:46 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +               		        {
here

2020-11-16 14:47 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +					UVs.Add (new Vector2 (tU * scaleU, tV * scaleV));
trailing spaces here

2020-11-16 14:47 UTC, lewa-j commented
Fix identation and trailing faces please.

2020-11-16 14:55 UTC, Fronkln commented
I hate it when Github does this, i'll take a quick look

2020-11-16 15:29 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +            int lmx = 0; lmy = 0;
Now it won't compile

2020-11-16 15:30 UTC, lewa-j commented on Assets/Code/Read/SourceBSPLoader.cs
> +            if (usrcSettings.Inst.lightmaps && (tiFlags & SourceBSPStructs.SURF_NOLIGHT) == 0)
why?

2020-11-16 15:31 UTC, lewa-j commented
I has nothing to do with github. I believe the cause is your ide. Now we have mixed up spaces and tabs.

2020-11-16 15:31 UTC, Fronkln commented
Visual studio is playing some big games with me right now, despite the code appearing normal in github, i'll reopen this when im sure its fixed

2020-11-16 15:31 UTC, closed without merging

2020-11-16 15:32 UTC, lewa-j commented
Try to open files in something like notepad++. It can show you where spaces and tab characters are

2020-11-16 15:35 UTC, lewa-j commented
And instead of closing and opening new PRs, and creating many unnecessary commits, you should learn how to force push commits.

2020-11-17 04:41 UTC, antim0118 commented on Assets/Code/Read/SourceBSPLoader.cs
> +            int lmx = 0; lmy = 0;
wtf